config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :contacts
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_rich_text :body

  def full_name
    [first_name, last_name].compact.join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    if @contact = Contact.create(contact_params)
      session[:contact_request_sent] = true
      UserMailer.with(contact: @contact).new_contact_request.deliver_later
      redirect_to root_path, notice: "Your contact request was sent. I will be in touch soon."
    else
      render :new
    end
  end

  private


  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone, :email, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/new.html.erb
<%= turbo_frame_tag :new_contact do %>
  <h3 class="text-indigo-200 text-3xl text-center mb-8"> Contact Me </h3>
  <%= form_with model: @contact do |f| %>
    <div class="grid max-w-5xl w-full mx-auto px-4 mx:px-0">
      <div class="flex flex-col md:flex-row gap-4">
        <div class="flex flex-col w-full md:w-1/3">
          <%= f.label :first_name, class: "text-indigo-100" %>
          <%= f.text_field :first_name, class: "w-full bg-indigo-400 rounded-full text-indigo-200 focus:ring-4 focus:ring-indigo-300" %>
        </div>
        <div class="flex flex-col w-full">
          <%= f.label :last_name, class: "text-indigo-100" %>
          <%= f.text_field :last_name, class: "w-full bg-indigo-400 rounded-full text-indigo-200 focus:ring-4 focus:ring-indigo-300" %>
        </div>
      </div>

      <div class="flex flex-col mt-4">
        <%= f.label :phone, class: "text-indigo-100" %>
        <%= f.text_field :phone, class: "w-full bg-indigo-400 rounded-full text-indigo-200 focus:ring-4 focus:ring-indigo-300" %>
      </div>


      <div class="flex flex-col mt-4">
        <%= f.label :email, class: "text-indigo-100" %>
        <%= f.text_field :email, class: "w-full bg-indigo-400 rounded-full text-indigo-200 focus:ring-4 focus:ring-indigo-300" %>
      </div>

      <div class="flex flex-col mt-4">
        <%= f.label :body, class: "text-indigo-100" %>
        <%= f.rich_text_area :body, class: "w-full bg-indigo-400 rounded-lg text-indigo-200 focus:ring-4 focus:ring-indigo-300" %>
      </div>

      <br/>

      <%= f.submit "Send message", class: "bg-blue-500 text-blue-50 p-2 cursor-pointer rounded-full" %>
    </div>

  <% end %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hire Enoch Tamulonis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex flex-col items-center py-24 bg-gradient-to-r from-indigo-500 to-blue-500 min-h-[100vh] px-4 md:px-0">
  <div class="max-w-5xl w-full">
    <h1 class="text-5xl md:text-7xl text-indigo-100 font-bold"> Enoch Tamulonis </h1>
    <p class="text-2xl text-indigo-100"> I build web and mobile apps using Ruby on Rails, Hotwire, and Tailwind CSS </p>

    <div class="mt-8 bg-gray-700/75 max-w-xl rounded-lg p-3">
      <h3 class="text-indigo-200"> Get to know me </h3>
      <p class="text-xl text-indigo-100">
        Hey I'm Enoch, I'm a software engineer based out of Austin, Texas.
        I've been coding since 2016 when I started coding to build solutions for myself such as eccomerce stores and hosting for my music. As I advanced and got more experience I started doing consulting work and realized I love working with clients and solving their issues
      </p>
    </div>

    <div class="mt-8 bg-gray-700/75 max-w-xl rounded-lg p-3">
      <h3 class="text-indigo-200"> My experience </h3>
      <p class="text-xl text-indigo-100">
        I have worked with many companies from startups to enterprise level apps, 
        the scopes of the projects ranged from updates and backlog work to building new features,
        and new greenfield applications.
      </p>
    </div>

    <div class="mt-8 p-3">
      <h3 class="text-indigo-200"> Companies I've worked with </h3>
      <div class="flex gap-8 md:gap-16 mt-4 overflow-x-auto">
        <%= link_to "https://www.wavclouds.com", target: "_new" do %>
          <%= image_tag "wavclouds.png", class: "w-32 object-cover" %>
        <% end %>

        <%= link_to "https://www.sunpower.com", target: "_new", class: "flex items-center" do %>
          <%= image_tag "SunPower.png", class: "w-64 object-cover" %>
        <% end %>

        <%= link_to "https://www.sba.gov", target: "_new", class: "flex items-center" do %>
          <%= image_tag "sbagov.svg", class: "w-32 object-cover" %>
        <% end %>

        <%= link_to "https://www.thegnar.com", target: "_new", class: "flex items-center" do %>
          <%= image_tag "thegnarcompany.png", class: "w-32 object-cover" %>
        <% end %>

        <%= link_to "https://www.plasticsurgerypractice.com", target: "_new", class: "flex items-center" do %>
          <%= image_tag "psp.png", class: "w-32 object-cover" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

<div class="bg-gradient-to-l from-indigo-600 to-blue-600 h-screen pt-8">
  <% if !session[:contact_request_sent] === true %>
    <%= turbo_frame_tag :new_contact, src: new_contact_path %>
  <% else %>
    <%= turbo_frame_tag :new_contact do %>
      <div class="w-full flex justify-center">
        <span class="text-center text-2xl text-indigo-100"> Your message was sent. I will be in touch soon </span>
      </div>
    <% end %>
  <% end %>
</div>